name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Get Previous tag
        uses: WyriHaximus/github-action-get-previous-tag@v1.4
        with:
          fallback: v1.0 init
        id: previoustag

      - name: Update Version Number
        run:
          echo "\newcommand{\Version}{${{ steps.previoustag.outputs.tag  }}}" > src/Settings/Version.tex


      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          latexmk_use_lualatex: true
          root_file: |
            CheatSheet_Player.tex
            CheatSheet_Player_LS.tex

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            src/CheatSheet_Player.tex
            src/CheatSheet_Player_LS.tex