on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  Create_Release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Update Version Number
        run:
          echo "\newcommand{\Version}{${{ github.ref_name }}}" > src/Settings/Version.tex

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          latexmk_use_lualatex: true
          root_file: |
            CheatSheet_Player.tex
            CheatSheet_Player_LS.tex
            CheatSheet_GM.tex

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          files: |
            src/CheatSheet_Player.pdf
            src/CheatSheet_Player_LS.pdf
            src/CheatSheet_GM.pdf